import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1778421828322 implements MigrationInterface {
    name = 'InitialSchema1778421828322'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "drivers_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trip_orders" DROP CONSTRAINT "trip_orders_order_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trip_orders" DROP CONSTRAINT "trip_orders_trip_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "trips_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "trips_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "gps_locations" DROP CONSTRAINT "gps_locations_trip_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "gps_locations" DROP CONSTRAINT "gps_locations_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "alerts_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "alerts_trip_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "alerts_vehicle_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" DROP CONSTRAINT "driver_kpi_driver_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gps_vehicle_recorded_at"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "photo_url" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "signature_url" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'driver', 'dispatcher')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'driver'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refresh_token_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refresh_token_hash" text`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "UQ_8e224f1b8f05ace7cfc7c76d03b" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "full_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "license_class"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "license_class" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."driver_status" RENAME TO "driver_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."drivers_status_enum" AS ENUM('available', 'on_trip', 'off_duty')`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" TYPE "public"."drivers_status_enum" USING "status"::"text"::"public"."drivers_status_enum"`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" SET DEFAULT 'off_duty'`);
        await queryRunner.query(`DROP TYPE "public"."driver_status_old"`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "avatar_url" character varying`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "vehicles_plate_number_key"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "plate_number"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "plate_number" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "UQ_a7eeeb4b551b2629dd9ee964134" UNIQUE ("plate_number")`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_type" RENAME TO "vehicle_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_type_enum" AS ENUM('small', 'medium', 'large')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "type" TYPE "public"."vehicles_type_enum" USING "type"::"text"::"public"."vehicles_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_type_old"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "current_load_kg" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_status" RENAME TO "vehicle_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_status_enum" AS ENUM('available', 'delivering', 'maintenance')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" TYPE "public"."vehicles_status_enum" USING "status"::"text"::"public"."vehicles_status_enum"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" SET DEFAULT 'available'`);
        await queryRunner.query(`DROP TYPE "public"."vehicle_status_old"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "image_url" character varying`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "pickup_address"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "pickup_address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_address"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."order_status" RENAME TO "order_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'assigned', 'picked_up', 'delivering', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum" USING "status"::"text"::"public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."order_status_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TYPE "public"."trip_status" RENAME TO "trip_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."trips_status_enum" AS ENUM('pending', 'accepted', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" TYPE "public"."trips_status_enum" USING "status"::"text"::"public"."trips_status_enum"`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."trip_status_old"`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ALTER COLUMN "recorded_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ALTER COLUMN "recorded_at" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "vehicle_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type" RENAME TO "alert_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_type_enum" AS ENUM('speed_violation', 'route_deviation', 'abnormal_stop', 'incident')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alerts_type_enum" USING "type"::"text"::"public"."alerts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alert_type_old"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_severity" RENAME TO "alert_severity_old"`);
        await queryRunner.query(`CREATE TYPE "public"."alerts_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "severity" TYPE "public"."alerts_severity_enum" USING "severity"::"text"::"public"."alerts_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."alert_severity_old"`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "is_resolved" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "total_trips" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "completed_trips" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "completion_rate" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "total_violations" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "speed_violations" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "route_violations" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "kpi_score" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ed605b32552f6f03cdc154153" ON "gps_locations" ("vehicle_id", "recorded_at") `);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_orders" ADD CONSTRAINT "FK_49dcfadcd6516ce31866f31eacf" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_orders" ADD CONSTRAINT "FK_eb3ae7e919ef2a41341d99b13d6" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_ab4b806373c2ee43946679d572e" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ADD CONSTRAINT "FK_a6fd64c4d252272725d9716af40" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ADD CONSTRAINT "FK_ef70b89fb4eb8f22d5e6adbdd08" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_e9e6791b945e74a123fc1316381" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_74dd85f46da0c401a52b82aa8f5" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "FK_6e903097eae826928bc6030b5c5" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ADD CONSTRAINT "FK_8122b6c9ed335bccb4efd0c4c3e" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "driver_kpi" DROP CONSTRAINT "FK_8122b6c9ed335bccb4efd0c4c3e"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_6e903097eae826928bc6030b5c5"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_74dd85f46da0c401a52b82aa8f5"`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP CONSTRAINT "FK_e9e6791b945e74a123fc1316381"`);
        await queryRunner.query(`ALTER TABLE "gps_locations" DROP CONSTRAINT "FK_ef70b89fb4eb8f22d5e6adbdd08"`);
        await queryRunner.query(`ALTER TABLE "gps_locations" DROP CONSTRAINT "FK_a6fd64c4d252272725d9716af40"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_44d36110fb38f45c2f15c946ddb"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_ab4b806373c2ee43946679d572e"`);
        await queryRunner.query(`ALTER TABLE "trip_orders" DROP CONSTRAINT "FK_eb3ae7e919ef2a41341d99b13d6"`);
        await queryRunner.query(`ALTER TABLE "trip_orders" DROP CONSTRAINT "FK_49dcfadcd6516ce31866f31eacf"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_9c2e0a8772c9e43b32f57bfcfcc"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "FK_8e224f1b8f05ace7cfc7c76d03b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ed605b32552f6f03cdc154153"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "kpi_score" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "route_violations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "speed_violations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "total_violations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "completion_rate" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "completed_trips" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ALTER COLUMN "total_trips" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "alerts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "is_resolved" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."alert_severity_old" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "severity" TYPE "public"."alert_severity_old" USING "severity"::"text"::"public"."alert_severity_old"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_severity_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_severity_old" RENAME TO "alert_severity"`);
        await queryRunner.query(`CREATE TYPE "public"."alert_type_old" AS ENUM('speed_violation', 'route_deviation', 'abnormal_stop', 'incident')`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "type" TYPE "public"."alert_type_old" USING "type"::"text"::"public"."alert_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."alerts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."alert_type_old" RENAME TO "alert_type"`);
        await queryRunner.query(`ALTER TABLE "alerts" ALTER COLUMN "vehicle_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ALTER COLUMN "recorded_at" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ALTER COLUMN "recorded_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trips" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "trips" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."trip_status_old" AS ENUM('pending', 'accepted', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" TYPE "public"."trip_status_old" USING "status"::"text"::"public"."trip_status_old"`);
        await queryRunner.query(`ALTER TABLE "trips" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."trips_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."trip_status_old" RENAME TO "trip_status"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_old" AS ENUM('pending', 'assigned', 'picked_up', 'delivering', 'delivered', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."order_status_old" USING "status"::"text"::"public"."order_status_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."order_status_old" RENAME TO "order_status"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "delivery_address"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "delivery_address" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "pickup_address"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "pickup_address" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "image_url" text`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_status_old" AS ENUM('available', 'delivering', 'maintenance')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" TYPE "public"."vehicle_status_old" USING "status"::"text"::"public"."vehicle_status_old"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "status" SET DEFAULT 'available'`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_status_old" RENAME TO "vehicle_status"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "current_load_kg" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."vehicle_type_old" AS ENUM('small', 'medium', 'large')`);
        await queryRunner.query(`ALTER TABLE "vehicles" ALTER COLUMN "type" TYPE "public"."vehicle_type_old" USING "type"::"text"::"public"."vehicle_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."vehicle_type_old" RENAME TO "vehicle_type"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "UQ_a7eeeb4b551b2629dd9ee964134"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP COLUMN "plate_number"`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD "plate_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_plate_number_key" UNIQUE ("plate_number")`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "avatar_url"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "avatar_url" text`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."driver_status_old" AS ENUM('available', 'on_trip', 'off_duty')`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" TYPE "public"."driver_status_old" USING "status"::"text"::"public"."driver_status_old"`);
        await queryRunner.query(`ALTER TABLE "drivers" ALTER COLUMN "status" SET DEFAULT 'off_duty'`);
        await queryRunner.query(`DROP TYPE "public"."drivers_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."driver_status_old" RENAME TO "driver_status"`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "license_class"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "license_class" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "phone" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD "full_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "drivers" DROP CONSTRAINT "UQ_8e224f1b8f05ace7cfc7c76d03b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refresh_token_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refresh_token_hash" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('admin', 'driver', 'dispatcher')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'driver'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "signature_url"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "photo_url"`);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "idx_gps_vehicle_recorded_at" ON "gps_locations" ("recorded_at", "vehicle_id") `);
        await queryRunner.query(`ALTER TABLE "driver_kpi" ADD CONSTRAINT "driver_kpi_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "alerts_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "alerts_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alerts" ADD CONSTRAINT "alerts_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ADD CONSTRAINT "gps_locations_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "gps_locations" ADD CONSTRAINT "gps_locations_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "trips_vehicle_id_fkey" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "trips_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_orders" ADD CONSTRAINT "trip_orders_trip_id_fkey" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_orders" ADD CONSTRAINT "trip_orders_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "drivers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drivers" ADD CONSTRAINT "drivers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
